import com.demo.DroolsDemo.CallDetails


rule "R1: in general allow calls"
	when
		callObject: CallDetails()
	then
		callObject.setAllowDeny("allow");
		System.out.println("Rule R1: in general allow calls");
	end

rule "R2: when at_family_outing and business call"
	when
		callObject: CallDetails(Location=="at_family_outing", Call=="business")
	then
		if (callObject.getcallFrom()=="boss") { 
			callObject.setAllowDeny("allow");
			System.out.println("Rule R2: when at_family_outing && business call from boss then Allow");
			}
		else {
			callObject.setAllowDeny("deny");
			System.out.println("Rule R2: when at_family_outing && business call then Deny");
		}
		
	end

rule "R3: when at_work and family call"
	when
		callObject: CallDetails(Location=="at_work", Call=="family")
	then
		if (callObject.getcallFrom()=="son") { 
			callObject.setAllowDeny("allow");
			System.out.println("Rule R3: when at_work && family call && from son, then Allow");
			}
		else {
			callObject.setAllowDeny("deny");
			System.out.println("Rule R3: when at_work && family call then Deny");
		}
	end

