import com.demo.DroolsDemo.CallDetails

rule "R1: in general allow calls"
	when
		callObject: CallDetails()
	then
		callObject.setAllowDenyCall("allow");
		System.out.println("Rule R1: in general allow calls");
	end

rule "R2.1: when at_family_outing and business call"
	when
		callObject: CallDetails(Location=="at_family_outing", Call=="business")
	then
		callObject.setAllowDenyCall("deny");
		System.out.println("Rule R2: when at_family_outing && business call then Deny");
	end

rule "R2.2: when at_family_outing and business call from boss"
	when
		callObject: CallDetails(Location=="at_family_outing", Call=="business", CallFrom=="boss")
	then
		callObject.setAllowDenyCall("allow");
		System.out.println("Rule R2: when at_family_outing && business call from boss then Allow");
	end

rule "R3.1: when at_work and family call"
	when
		callObject: CallDetails(Location=="at_work", Call=="family")
	then
		callObject.setAllowDenyCall("deny");
		System.out.println("Rule R3: when at_work && family call then Deny");
	end

